	
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsAssistRequireMap.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:52
// </copyright>
//------------------------------------------------------------------------------

	using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace TY.SHMetroPlan.Data.Domain.Models.Mapping
{
    public class BsAssistRequireMap : EntityTypeConfiguration<BsAssistRequire>
    {
        public BsAssistRequireMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.Id)
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.UnitId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.UnitCode)
                .HasMaxLength(200);

            this.Property(t => t.Requirement)
                .HasMaxLength(200);

            this.Property(t => t.RequireCode)
                .HasMaxLength(200);

            // Table & Column Mappings
            this.ToTable("BsAssistRequire");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.UnitId).HasColumnName("UnitId");
            this.Property(t => t.UnitCode).HasColumnName("UnitCode");
            this.Property(t => t.Requirement).HasColumnName("Requirement");
            this.Property(t => t.RequireCode).HasColumnName("RequireCode");
            this.Property(t => t.IsEnabled).HasColumnName("IsEnabled");
            this.Property(t => t.CreateTime).HasColumnName("CreateTime");
            this.Property(t => t.UpdateTime).HasColumnName("UpdateTime");
            this.Property(t => t.RowVersion).HasColumnName("RowVersion");

            // Relationships
            this.HasOptional(t => t.BsAssistUnit)
                .WithMany(t => t.BsAssistRequires)
                .HasForeignKey(d => d.UnitId);

        }
    }
}
