	
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsCheckRangeMap.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:52
// </copyright>
//------------------------------------------------------------------------------

	using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace TY.SHMetroPlan.Data.Domain.Models.Mapping
{
    public class BsCheckRangeMap : EntityTypeConfiguration<BsCheckRange>
    {
        public BsCheckRangeMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.Id)
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.CheckArrayId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.CheckArrayCode)
                .HasMaxLength(200);

            this.Property(t => t.CheckRangeCode)
                .HasMaxLength(200);

            this.Property(t => t.CheckRangeName)
                .HasMaxLength(400);

            this.Property(t => t.FacilityTypeCode)
                .HasMaxLength(200);

            this.Property(t => t.EquipmentCode)
                .HasMaxLength(200);

            this.Property(t => t.Remark)
                .HasMaxLength(200);

            // Table & Column Mappings
            this.ToTable("BsCheckRange");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.CheckArrayId).HasColumnName("CheckArrayId");
            this.Property(t => t.CheckArrayCode).HasColumnName("CheckArrayCode");
            this.Property(t => t.CheckRangeCode).HasColumnName("CheckRangeCode");
            this.Property(t => t.CheckRangeType).HasColumnName("CheckRangeType");
            this.Property(t => t.CheckRangeName).HasColumnName("CheckRangeName");
            this.Property(t => t.FacilityTypeCode).HasColumnName("FacilityTypeCode");
            this.Property(t => t.EquipmentCode).HasColumnName("EquipmentCode");
            this.Property(t => t.DirectionMark).HasColumnName("DirectionMark");
            this.Property(t => t.StartMileage).HasColumnName("StartMileage");
            this.Property(t => t.EndMileage).HasColumnName("EndMileage");
            this.Property(t => t.IsEnabled).HasColumnName("IsEnabled");
            this.Property(t => t.Remark).HasColumnName("Remark");
            this.Property(t => t.CreateTime).HasColumnName("CreateTime");
            this.Property(t => t.UpdateTime).HasColumnName("UpdateTime");
            this.Property(t => t.RowVersion).HasColumnName("RowVersion");

            // Relationships
            this.HasOptional(t => t.BsCheckArray)
                .WithMany(t => t.BsCheckRanges)
                .HasForeignKey(d => d.CheckArrayId);

        }
    }
}
