	
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsLineFastenerMap.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:52
// </copyright>
//------------------------------------------------------------------------------

	using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace TY.SHMetroPlan.Data.Domain.Models.Mapping
{
    public class BsLineFastenerMap : EntityTypeConfiguration<BsLineFastener>
    {
        public BsLineFastenerMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.Id)
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.EquipmentId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.EquipmentCode)
                .HasMaxLength(200);

            this.Property(t => t.SleeperNo)
                .HasMaxLength(100);

            this.Property(t => t.FastenerType)
                .HasMaxLength(100);

            this.Property(t => t.FastenerNo)
                .HasMaxLength(100);

            this.Property(t => t.TrackType)
                .HasMaxLength(100);

            this.Property(t => t.TrackDrawNo)
                .HasMaxLength(100);

            this.Property(t => t.Remark)
                .IsFixedLength()
                .HasMaxLength(200);

            // Table & Column Mappings
            this.ToTable("BsLineFastener");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.EquipmentId).HasColumnName("EquipmentId");
            this.Property(t => t.EquipmentCode).HasColumnName("EquipmentCode");
            this.Property(t => t.SleeperType).HasColumnName("SleeperType");
            this.Property(t => t.SleeperNum).HasColumnName("SleeperNum");
            this.Property(t => t.SleeperNo).HasColumnName("SleeperNo");
            this.Property(t => t.FastenerType).HasColumnName("FastenerType");
            this.Property(t => t.FastenerNum).HasColumnName("FastenerNum");
            this.Property(t => t.FastenerNo).HasColumnName("FastenerNo");
            this.Property(t => t.TrackType).HasColumnName("TrackType");
            this.Property(t => t.TrackLength).HasColumnName("TrackLength");
            this.Property(t => t.TrackDrawNo).HasColumnName("TrackDrawNo");
            this.Property(t => t.Remark).HasColumnName("Remark");
            this.Property(t => t.SortId).HasColumnName("SortId");
            this.Property(t => t.CreateTime).HasColumnName("CreateTime");
            this.Property(t => t.UpdateTime).HasColumnName("UpdateTime");
            this.Property(t => t.RowVersion).HasColumnName("RowVersion");

            // Relationships
            this.HasOptional(t => t.BsFacilityEquipment)
                .WithMany(t => t.BsLineFasteners)
                .HasForeignKey(d => d.EquipmentId);

        }
    }
}
