	
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsMtReservoirMap.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:52
// </copyright>
//------------------------------------------------------------------------------

	using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace TY.SHMetroPlan.Data.Domain.Models.Mapping
{
    public class BsMtReservoirMap : EntityTypeConfiguration<BsMtReservoir>
    {
        public BsMtReservoirMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.Id)
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.ReservoirMaterialCode)
                .HasMaxLength(200);

            this.Property(t => t.ReservoirId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.ReservoirCode)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.SpecificationId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.SpecificationCode)
                .HasMaxLength(200);

            this.Property(t => t.Remark)
                .HasMaxLength(200);

            // Table & Column Mappings
            this.ToTable("BsMtReservoir");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.ReservoirMaterialCode).HasColumnName("ReservoirMaterialCode");
            this.Property(t => t.ReservoirId).HasColumnName("ReservoirId");
            this.Property(t => t.ReservoirCode).HasColumnName("ReservoirCode");
            this.Property(t => t.SpecificationId).HasColumnName("SpecificationId");
            this.Property(t => t.SpecificationCode).HasColumnName("SpecificationCode");
            this.Property(t => t.StockQuantity).HasColumnName("StockQuantity");
            this.Property(t => t.IsWarning).HasColumnName("IsWarning");
            this.Property(t => t.Remark).HasColumnName("Remark");
            this.Property(t => t.SortId).HasColumnName("SortId");
            this.Property(t => t.CreateTime).HasColumnName("CreateTime");
            this.Property(t => t.UpdateTime).HasColumnName("UpdateTime");
            this.Property(t => t.RowVersion).HasColumnName("RowVersion");

            // Relationships
            this.HasOptional(t => t.BsMtMateriale)
                .WithMany(t => t.BsMtReservoirs)
                .HasForeignKey(d => d.SpecificationId);
            this.HasOptional(t => t.BsWkReservoir)
                .WithMany(t => t.BsMtReservoirs)
                .HasForeignKey(d => d.ReservoirId);

        }
    }
}
