	
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsMtInvokeMap.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:52
// </copyright>
//------------------------------------------------------------------------------

	using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace TY.SHMetroPlan.Data.Domain.Models.Mapping
{
    public class BsMtInvokeMap : EntityTypeConfiguration<BsMtInvoke>
    {
        public BsMtInvokeMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.Id)
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.SpecificationId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.SpecificationCode)
                .HasMaxLength(200);

            this.Property(t => t.AreaId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.AreaCode)
                .HasMaxLength(200);

            this.Property(t => t.InvokingId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.InvokingDeptId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.InvokedId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.InvokedDeptId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.Remark)
                .HasMaxLength(200);

            // Table & Column Mappings
            this.ToTable("BsMtInvoke");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.SpecificationId).HasColumnName("SpecificationId");
            this.Property(t => t.SpecificationCode).HasColumnName("SpecificationCode");
            this.Property(t => t.AreaId).HasColumnName("AreaId");
            this.Property(t => t.AreaCode).HasColumnName("AreaCode");
            this.Property(t => t.InvokingId).HasColumnName("InvokingId");
            this.Property(t => t.InvokingDeptId).HasColumnName("InvokingDeptId");
            this.Property(t => t.InvokedId).HasColumnName("InvokedId");
            this.Property(t => t.InvokedDeptId).HasColumnName("InvokedDeptId");
            this.Property(t => t.InvokingDate).HasColumnName("InvokingDate");
            this.Property(t => t.InvokedDate).HasColumnName("InvokedDate");
            this.Property(t => t.InvokeReqNum).HasColumnName("InvokeReqNum");
            this.Property(t => t.InvokeRspNum).HasColumnName("InvokeRspNum");
            this.Property(t => t.InvokeState).HasColumnName("InvokeState");
            this.Property(t => t.Remark).HasColumnName("Remark");
            this.Property(t => t.SortId).HasColumnName("SortId");
            this.Property(t => t.CreateTime).HasColumnName("CreateTime");
            this.Property(t => t.UpdateTime).HasColumnName("UpdateTime");
            this.Property(t => t.RowVersion).HasColumnName("RowVersion");

            // Relationships
            this.HasOptional(t => t.BsMtMateriale)
                .WithMany(t => t.BsMtInvokes)
                .HasForeignKey(d => d.SpecificationId);

        }
    }
}
