	
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsMtInventoryMap.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:52
// </copyright>
//------------------------------------------------------------------------------

	using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace TY.SHMetroPlan.Data.Domain.Models.Mapping
{
    public class BsMtInventoryMap : EntityTypeConfiguration<BsMtInventory>
    {
        public BsMtInventoryMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.Id)
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.InventoryCode)
                .HasMaxLength(200);

            this.Property(t => t.SpecificationId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.SpecificationCode)
                .HasMaxLength(200);

            this.Property(t => t.AreaId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.AreaCode)
                .HasMaxLength(200);

            this.Property(t => t.DeptId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.DeptCode)
                .HasMaxLength(200);

            this.Property(t => t.Remark)
                .HasMaxLength(200);

            // Table & Column Mappings
            this.ToTable("BsMtInventory");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.InventoryCode).HasColumnName("InventoryCode");
            this.Property(t => t.SpecificationId).HasColumnName("SpecificationId");
            this.Property(t => t.SpecificationCode).HasColumnName("SpecificationCode");
            this.Property(t => t.StockQuantity).HasColumnName("StockQuantity");
            this.Property(t => t.AreaId).HasColumnName("AreaId");
            this.Property(t => t.AreaCode).HasColumnName("AreaCode");
            this.Property(t => t.DeptId).HasColumnName("DeptId");
            this.Property(t => t.DeptCode).HasColumnName("DeptCode");
            this.Property(t => t.Remark).HasColumnName("Remark");
            this.Property(t => t.SortId).HasColumnName("SortId");
            this.Property(t => t.CreateTime).HasColumnName("CreateTime");
            this.Property(t => t.UpdateTime).HasColumnName("UpdateTime");
            this.Property(t => t.RowVersion).HasColumnName("RowVersion");

            // Relationships
            this.HasOptional(t => t.BsMtMateriale)
                .WithMany(t => t.BsMtInventories)
                .HasForeignKey(d => d.SpecificationId);

        }
    }
}
