	
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsStationLubricatorMap.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:53
// </copyright>
//------------------------------------------------------------------------------

	using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace TY.SHMetroPlan.Data.Domain.Models.Mapping
{
    public class BsStationLubricatorMap : EntityTypeConfiguration<BsStationLubricator>
    {
        public BsStationLubricatorMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.Id)
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.EquipmentId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.EquipmentCode)
                .HasMaxLength(200);

            this.Property(t => t.CurveRadius)
                .HasMaxLength(100);

            this.Property(t => t.OilOutletPlateType)
                .HasMaxLength(200);

            this.Property(t => t.SensorMode)
                .HasMaxLength(200);

            this.Property(t => t.InspectionCycle)
                .HasMaxLength(200);

            this.Property(t => t.Remark)
                .HasMaxLength(200);

            // Table & Column Mappings
            this.ToTable("BsStationLubricator");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.EquipmentId).HasColumnName("EquipmentId");
            this.Property(t => t.EquipmentCode).HasColumnName("EquipmentCode");
            this.Property(t => t.InstallMileage).HasColumnName("InstallMileage");
            this.Property(t => t.InstallPosition).HasColumnName("InstallPosition");
            this.Property(t => t.InstallDate).HasColumnName("InstallDate");
            this.Property(t => t.UserDate).HasColumnName("UserDate");
            this.Property(t => t.CurveLength).HasColumnName("CurveLength");
            this.Property(t => t.CurveRadius).HasColumnName("CurveRadius");
            this.Property(t => t.OilTimes).HasColumnName("OilTimes");
            this.Property(t => t.Oilproportion).HasColumnName("Oilproportion");
            this.Property(t => t.OilOutletPlateType).HasColumnName("OilOutletPlateType");
            this.Property(t => t.SensorMode).HasColumnName("SensorMode");
            this.Property(t => t.InspectionCycle).HasColumnName("InspectionCycle");
            this.Property(t => t.Remark).HasColumnName("Remark");
            this.Property(t => t.SortId).HasColumnName("SortId");
            this.Property(t => t.CreateTime).HasColumnName("CreateTime");
            this.Property(t => t.UpdateTime).HasColumnName("UpdateTime");
            this.Property(t => t.RowVersion).HasColumnName("RowVersion");

            // Relationships
            this.HasOptional(t => t.BsFacilityEquipment)
                .WithMany(t => t.BsStationLubricators)
                .HasForeignKey(d => d.EquipmentId);

        }
    }
}
