	
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="Wx_CheckArrangeMap.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:53
// </copyright>
//------------------------------------------------------------------------------

	using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace TY.SHMetroPlan.Data.Domain.Models.Mapping
{
    public class Wx_CheckArrangeMap : EntityTypeConfiguration<Wx_CheckArrange>
    {
        public Wx_CheckArrangeMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.Id)
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.CheckProjectId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.ArrangeCode)
                .HasMaxLength(200);

            this.Property(t => t.ArrangeCotent)
                .HasMaxLength(400);

            this.Property(t => t.CheckLeaderCode)
                .HasMaxLength(200);

            this.Property(t => t.Workload)
                .HasMaxLength(200);

            this.Property(t => t.Remark)
                .IsFixedLength()
                .HasMaxLength(200);

            // Table & Column Mappings
            this.ToTable("Wx_CheckArrange");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.CheckProjectId).HasColumnName("CheckProjectId");
            this.Property(t => t.ArrangeCode).HasColumnName("ArrangeCode");
            this.Property(t => t.ArrangeCotent).HasColumnName("ArrangeCotent");
            this.Property(t => t.TaskState).HasColumnName("TaskState");
            this.Property(t => t.CheckLeaderCode).HasColumnName("CheckLeaderCode");
            this.Property(t => t.ArtificialNum).HasColumnName("ArtificialNum");
            this.Property(t => t.Workload).HasColumnName("Workload");
            this.Property(t => t.PracticalNumr).HasColumnName("PracticalNumr");
            this.Property(t => t.PlanStartDate).HasColumnName("PlanStartDate");
            this.Property(t => t.PlanEndDate).HasColumnName("PlanEndDate");
            this.Property(t => t.IsFinished).HasColumnName("IsFinished");
            this.Property(t => t.Remark).HasColumnName("Remark");
            this.Property(t => t.CreateTime).HasColumnName("CreateTime");
            this.Property(t => t.UpdateTime).HasColumnName("UpdateTime");
            this.Property(t => t.RowVersion).HasColumnName("RowVersion");

            // Relationships
            this.HasOptional(t => t.Wx_CheckProject)
                .WithMany(t => t.Wx_CheckArrange)
                .HasForeignKey(d => d.CheckProjectId);

        }
    }
}
