	
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="Wx_YearCheckPlanMap.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:53
// </copyright>
//------------------------------------------------------------------------------

	using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace TY.SHMetroPlan.Data.Domain.Models.Mapping
{
    public class Wx_YearCheckPlanMap : EntityTypeConfiguration<Wx_YearCheckPlan>
    {
        public Wx_YearCheckPlanMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.Id)
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.YearPlanId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.TaskName)
                .HasMaxLength(200);

            this.Property(t => t.TaskCode)
                .HasMaxLength(200);

            this.Property(t => t.Remark)
                .HasMaxLength(200);

            // Table & Column Mappings
            this.ToTable("Wx_YearCheckPlan");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.YearPlanId).HasColumnName("YearPlanId");
            this.Property(t => t.TaskName).HasColumnName("TaskName");
            this.Property(t => t.TaskCode).HasColumnName("TaskCode");
            this.Property(t => t.TaskState).HasColumnName("TaskState");
            this.Property(t => t.PlanStartDate).HasColumnName("PlanStartDate");
            this.Property(t => t.PlanEndDate).HasColumnName("PlanEndDate");
            this.Property(t => t.IsFinished).HasColumnName("IsFinished");
            this.Property(t => t.Remark).HasColumnName("Remark");
            this.Property(t => t.CreateTime).HasColumnName("CreateTime");
            this.Property(t => t.UpdateTime).HasColumnName("UpdateTime");
            this.Property(t => t.RowVersion).HasColumnName("RowVersion");

            // Relationships
            this.HasOptional(t => t.Wx_RepairYearPlan)
                .WithMany(t => t.Wx_YearCheckPlan)
                .HasForeignKey(d => d.YearPlanId);

        }
    }
}
