	
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="YwDiseasePushMap.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:54
// </copyright>
//------------------------------------------------------------------------------

	using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace TY.SHMetroPlan.Data.Domain.Models.Mapping
{
    public class YwDiseasePushMap : EntityTypeConfiguration<YwDiseasePush>
    {
        public YwDiseasePushMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.Id)
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.RecordCode)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.DiseaseCode)
                .HasMaxLength(200);

            this.Property(t => t.SenderId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.RecevDptId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.ReceiveId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.PushRecord)
                .HasMaxLength(200);

            this.Property(t => t.InspectionOption)
                .HasMaxLength(200);

            // Table & Column Mappings
            this.ToTable("YwDiseasePush");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.RecordCode).HasColumnName("RecordCode");
            this.Property(t => t.DiseaseCode).HasColumnName("DiseaseCode");
            this.Property(t => t.SenderId).HasColumnName("SenderId");
            this.Property(t => t.RecevDptId).HasColumnName("RecevDptId");
            this.Property(t => t.ReceiveId).HasColumnName("ReceiveId");
            this.Property(t => t.PushRecord).HasColumnName("PushRecord");
            this.Property(t => t.PushDate).HasColumnName("PushDate");
            this.Property(t => t.InspectionOption).HasColumnName("InspectionOption");
            this.Property(t => t.CreateTime).HasColumnName("CreateTime");
            this.Property(t => t.UpdateTime).HasColumnName("UpdateTime");
            this.Property(t => t.RowVersion).HasColumnName("RowVersion");

            // Relationships
            this.HasOptional(t => t.YwDiseaseRecord)
                .WithMany(t => t.YwDiseasePushes)
                .HasForeignKey(d => d.RecordCode);

        }
    }
}
