	
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="YwDiseasePlanDetailEmpMap.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:54
// </copyright>
//------------------------------------------------------------------------------

	using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace TY.SHMetroPlan.Data.Domain.Models.Mapping
{
    public class YwDiseasePlanDetailEmpMap : EntityTypeConfiguration<YwDiseasePlanDetailEmp>
    {
        public YwDiseasePlanDetailEmpMap()
        {
            // Primary Key
            this.HasKey(t => t.Id);

            // Properties
            this.Property(t => t.Id)
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.PlanDetailId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.PlanDetailCode)
                .HasMaxLength(200);

            this.Property(t => t.WorkAreaId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.WorkAreaCode)
                .HasMaxLength(200);

            this.Property(t => t.LineId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.LineCode)
                .HasMaxLength(200);

            this.Property(t => t.EmpId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.EmpCode)
                .HasMaxLength(200);

            // Table & Column Mappings
            this.ToTable("YwDiseasePlanDetailEmp");
            this.Property(t => t.Id).HasColumnName("Id");
            this.Property(t => t.PlanDetailId).HasColumnName("PlanDetailId");
            this.Property(t => t.PlanDetailCode).HasColumnName("PlanDetailCode");
            this.Property(t => t.WorkAreaId).HasColumnName("WorkAreaId");
            this.Property(t => t.WorkAreaCode).HasColumnName("WorkAreaCode");
            this.Property(t => t.LineId).HasColumnName("LineId");
            this.Property(t => t.LineCode).HasColumnName("LineCode");
            this.Property(t => t.EmpId).HasColumnName("EmpId");
            this.Property(t => t.EmpCode).HasColumnName("EmpCode");
            this.Property(t => t.CreateTime).HasColumnName("CreateTime");
            this.Property(t => t.UpdateTime).HasColumnName("UpdateTime");
            this.Property(t => t.RowVersion).HasColumnName("RowVersion");

            // Relationships
            this.HasOptional(t => t.YwDiseasePlanDetail)
                .WithMany(t => t.YwDiseasePlanDetailEmps)
                .HasForeignKey(d => d.PlanDetailId);

        }
    }
}
