//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsFacilityEquipment.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:52
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [BsFacilityEquipment]
    /// </summary>
    [Serializable]
    public partial class BsFacilityEquipment : BaseEntity
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public BsFacilityEquipment()
        {
            this.BsEquipmentConfigs = new List<BsEquipmentConfig>();
            this.BsLineFasteners = new List<BsLineFastener>();
            this.BsStationLubricators = new List<BsStationLubricator>();
            this.BsLineRails = new List<BsLineRail>();
            this.BsSectionTurnouts = new List<BsSectionTurnout>();
            this.BsFacilityEquipment1 = new List<BsFacilityEquipment>();
        }

        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [LineId]
        /// </summary>
        public string LineId { get; set; }
        /// <summary>
        /// [LineCode]
        /// </summary>
        public string LineCode { get; set; }
        /// <summary>
        /// [FacilityTypeId]
        /// </summary>
        public string FacilityTypeId { get; set; }
        /// <summary>
        /// [FacilityTypeCode]
        /// </summary>
        public string FacilityTypeCode { get; set; }
        /// <summary>
        /// [EquipmentName]
        /// </summary>
        public string EquipmentName { get; set; }
        /// <summary>
        /// [EquipmentCode]
        /// </summary>
        public string EquipmentCode { get; set; }
        /// <summary>
        /// [DirectionMark]
        /// </summary>
        public Nullable<int> DirectionMark { get; set; }
        /// <summary>
        /// [IsTurnoutArea]
        /// </summary>
        public Nullable<int> IsTurnoutArea { get; set; }
        /// <summary>
        /// [IsEnabled]
        /// </summary>
        public Nullable<int> IsEnabled { get; set; }
        /// <summary>
        /// [StartMileage]
        /// </summary>
        public Nullable<decimal> StartMileage { get; set; }
        /// <summary>
        /// [EndMileage]
        /// </summary>
        public Nullable<decimal> EndMileage { get; set; }
        /// <summary>
        /// [Remark]
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// [ParentId]
        /// </summary>
        public string ParentId { get; set; }
        /// <summary>
        /// [ParentCode]
        /// </summary>
        public string ParentCode { get; set; }
        /// <summary>
        /// [SortId]
        /// </summary>
        public Nullable<int> SortId { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航集合：BsEquipmentConfigs
        /// </summary>
        public virtual ICollection<BsEquipmentConfig> BsEquipmentConfigs { get; set; }
        /// <summary>
        /// 导航属性：BsFacilityCatetory
        /// </summary>
        public virtual BsFacilityCatetory BsFacilityCatetory { get; set; }
        /// <summary>
        /// 导航集合：BsLineFasteners
        /// </summary>
        public virtual ICollection<BsLineFastener> BsLineFasteners { get; set; }
        /// <summary>
        /// 导航集合：BsStationLubricators
        /// </summary>
        public virtual ICollection<BsStationLubricator> BsStationLubricators { get; set; }
        /// <summary>
        /// 导航集合：BsLineRails
        /// </summary>
        public virtual ICollection<BsLineRail> BsLineRails { get; set; }
        /// <summary>
        /// 导航属性：BsLineInfo
        /// </summary>
        public virtual BsLineInfo BsLineInfo { get; set; }
        /// <summary>
        /// 导航集合：BsSectionTurnouts
        /// </summary>
        public virtual ICollection<BsSectionTurnout> BsSectionTurnouts { get; set; }
        /// <summary>
        /// 导航集合：BsFacilityEquipment1
        /// </summary>
        public virtual ICollection<BsFacilityEquipment> BsFacilityEquipment1 { get; set; }
        /// <summary>
        /// 导航属性：BsFacilityEquipment2
        /// </summary>
        public virtual BsFacilityEquipment BsFacilityEquipment2 { get; set; }
    }
}
