//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsLineRail.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:52
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [BsLineRail]
    /// </summary>
    [Serializable]
    public partial class BsLineRail : BaseEntity
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public BsLineRail()
        {
            this.BsLineCurves = new List<BsLineCurve>();
        }

        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [EquipmentId]
        /// </summary>
        public string EquipmentId { get; set; }
        /// <summary>
        /// [EquipmentCode]
        /// </summary>
        public string EquipmentCode { get; set; }
        /// <summary>
        /// [RailMileage]
        /// </summary>
        public Nullable<decimal> RailMileage { get; set; }
        /// <summary>
        /// [RailLength]
        /// </summary>
        public Nullable<decimal> RailLength { get; set; }
        /// <summary>
        /// [StockMark]
        /// </summary>
        public Nullable<int> StockMark { get; set; }
        /// <summary>
        /// [IsCurveRail]
        /// </summary>
        public Nullable<int> IsCurveRail { get; set; }
        /// <summary>
        /// [RailNo]
        /// </summary>
        public Nullable<int> RailNo { get; set; }
        /// <summary>
        /// [RailType]
        /// </summary>
        public string RailType { get; set; }
        /// <summary>
        /// [JoinType]
        /// </summary>
        public string JoinType { get; set; }
        /// <summary>
        /// [RailCategory]
        /// </summary>
        public string RailCategory { get; set; }
        /// <summary>
        /// [RailProduce]
        /// </summary>
        public string RailProduce { get; set; }
        /// <summary>
        /// [ProductDate]
        /// </summary>
        public Nullable<System.DateTime> ProductDate { get; set; }
        /// <summary>
        /// [InstallDate]
        /// </summary>
        public Nullable<System.DateTime> InstallDate { get; set; }
        /// <summary>
        /// [Remark]
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// [SortId]
        /// </summary>
        public Nullable<int> SortId { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航属性：BsFacilityEquipment
        /// </summary>
        public virtual BsFacilityEquipment BsFacilityEquipment { get; set; }
        /// <summary>
        /// 导航集合：BsLineCurves
        /// </summary>
        public virtual ICollection<BsLineCurve> BsLineCurves { get; set; }
    }
}
