//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsLineFastener.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:52
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [BsLineFastener]
    /// </summary>
    [Serializable]
    public partial class BsLineFastener : BaseEntity
    {
        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [EquipmentId]
        /// </summary>
        public string EquipmentId { get; set; }
        /// <summary>
        /// [EquipmentCode]
        /// </summary>
        public string EquipmentCode { get; set; }
        /// <summary>
        /// [SleeperType]
        /// </summary>
        public Nullable<int> SleeperType { get; set; }
        /// <summary>
        /// [SleeperNum]
        /// </summary>
        public Nullable<int> SleeperNum { get; set; }
        /// <summary>
        /// [SleeperNo]
        /// </summary>
        public string SleeperNo { get; set; }
        /// <summary>
        /// [FastenerType]
        /// </summary>
        public string FastenerType { get; set; }
        /// <summary>
        /// [FastenerNum]
        /// </summary>
        public Nullable<int> FastenerNum { get; set; }
        /// <summary>
        /// [FastenerNo]
        /// </summary>
        public string FastenerNo { get; set; }
        /// <summary>
        /// [TrackType]
        /// </summary>
        public string TrackType { get; set; }
        /// <summary>
        /// [TrackLength]
        /// </summary>
        public Nullable<decimal> TrackLength { get; set; }
        /// <summary>
        /// [TrackDrawNo]
        /// </summary>
        public string TrackDrawNo { get; set; }
        /// <summary>
        /// [Remark]
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// [SortId]
        /// </summary>
        public Nullable<int> SortId { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航属性：BsFacilityEquipment
        /// </summary>
        public virtual BsFacilityEquipment BsFacilityEquipment { get; set; }
    }
}
