//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsLineCurve.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:52
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [BsLineCurve]
    /// </summary>
    [Serializable]
    public partial class BsLineCurve : BaseEntity
    {
        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [RailId]
        /// </summary>
        public string RailId { get; set; }
        /// <summary>
        /// [RailCode]
        /// </summary>
        public string RailCode { get; set; }
        /// <summary>
        /// [CurveName]
        /// </summary>
        public string CurveName { get; set; }
        /// <summary>
        /// [CurveCode]
        /// </summary>
        public string CurveCode { get; set; }
        /// <summary>
        /// [CurveDirection]
        /// </summary>
        public Nullable<int> CurveDirection { get; set; }
        /// <summary>
        /// [CurveRadius]
        /// </summary>
        public Nullable<decimal> CurveRadius { get; set; }
        /// <summary>
        /// [CurveAngle]
        /// </summary>
        public string CurveAngle { get; set; }
        /// <summary>
        /// [CurveLength]
        /// </summary>
        public Nullable<decimal> CurveLength { get; set; }
        /// <summary>
        /// [LongChainLength]
        /// </summary>
        public Nullable<decimal> LongChainLength { get; set; }
        /// <summary>
        /// [StartRelaxation]
        /// </summary>
        public Nullable<decimal> StartRelaxation { get; set; }
        /// <summary>
        /// [EndRelaxation]
        /// </summary>
        public Nullable<decimal> EndRelaxation { get; set; }
        /// <summary>
        /// [SuperHigh]
        /// </summary>
        public Nullable<decimal> SuperHigh { get; set; }
        /// <summary>
        /// [Widen]
        /// </summary>
        public Nullable<decimal> Widen { get; set; }
        /// <summary>
        /// [MaxSpeed]
        /// </summary>
        public Nullable<decimal> MaxSpeed { get; set; }
        /// <summary>
        /// [Remark]
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// [SortId]
        /// </summary>
        public Nullable<int> SortId { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航属性：BsLineRail
        /// </summary>
        public virtual BsLineRail BsLineRail { get; set; }
    }
}
