//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsMtPurchase.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:52
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [BsMtPurchase]
    /// </summary>
    [Serializable]
    public partial class BsMtPurchase : BaseEntity
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public BsMtPurchase()
        {
            this.BsMtAssigneds = new List<BsMtAssigned>();
            this.BsMtWorkflows = new List<BsMtWorkflow>();
        }

        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [MaterialApplyCode]
        /// </summary>
        public string MaterialApplyCode { get; set; }
        /// <summary>
        /// [RecordId]
        /// </summary>
        public string RecordId { get; set; }
        /// <summary>
        /// [WorkflowId]
        /// </summary>
        public string WorkflowId { get; set; }
        /// <summary>
        /// [RecordCode]
        /// </summary>
        public string RecordCode { get; set; }
        /// <summary>
        /// [ReservoirCode]
        /// </summary>
        public string ReservoirCode { get; set; }
        /// <summary>
        /// [SpecificationId]
        /// </summary>
        public string SpecificationId { get; set; }
        /// <summary>
        /// [SpecificationCode]
        /// </summary>
        public string SpecificationCode { get; set; }
        /// <summary>
        /// [PurchaseQuantity]
        /// </summary>
        public Nullable<int> PurchaseQuantity { get; set; }
        /// <summary>
        /// [ApplyDate]
        /// </summary>
        public Nullable<System.DateTime> ApplyDate { get; set; }
        /// <summary>
        /// [ApplyCls]
        /// </summary>
        public Nullable<int> ApplyCls { get; set; }
        /// <summary>
        /// [IsEnabled]
        /// </summary>
        public Nullable<int> IsEnabled { get; set; }
        /// <summary>
        /// [PurchaseState]
        /// </summary>
        public Nullable<int> PurchaseState { get; set; }
        /// <summary>
        /// [ApprovalType]
        /// </summary>
        public Nullable<int> ApprovalType { get; set; }
        /// <summary>
        /// [ApprovalStatus]
        /// </summary>
        public Nullable<int> ApprovalStatus { get; set; }
        /// <summary>
        /// [IsUrgent]
        /// </summary>
        public Nullable<int> IsUrgent { get; set; }
        /// <summary>
        /// [Remark]
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// [SortId]
        /// </summary>
        public Nullable<int> SortId { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航集合：BsMtAssigneds
        /// </summary>
        public virtual ICollection<BsMtAssigned> BsMtAssigneds { get; set; }
        /// <summary>
        /// 导航属性：BsMtMateriale
        /// </summary>
        public virtual BsMtMateriale BsMtMateriale { get; set; }
        /// <summary>
        /// 导航集合：BsMtWorkflows
        /// </summary>
        public virtual ICollection<BsMtWorkflow> BsMtWorkflows { get; set; }
        /// <summary>
        /// 导航属性：BsMtRecord
        /// </summary>
        public virtual BsMtRecord BsMtRecord { get; set; }
    }
}
