//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsSectionTurnout.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:53
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [BsSectionTurnout]
    /// </summary>
    [Serializable]
    public partial class BsSectionTurnout : BaseEntity
    {
        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [EquipmentId]
        /// </summary>
        public string EquipmentId { get; set; }
        /// <summary>
        /// [EquipmentCode]
        /// </summary>
        public string EquipmentCode { get; set; }
        /// <summary>
        /// [TurnoutType]
        /// </summary>
        public Nullable<int> TurnoutType { get; set; }
        /// <summary>
        /// [ImageNum]
        /// </summary>
        public string ImageNum { get; set; }
        /// <summary>
        /// [RunType]
        /// </summary>
        public Nullable<int> RunType { get; set; }
        /// <summary>
        /// [RailType]
        /// </summary>
        public string RailType { get; set; }
        /// <summary>
        /// [FrogNum]
        /// </summary>
        public Nullable<int> FrogNum { get; set; }
        /// <summary>
        /// [FrogStructure]
        /// </summary>
        public string FrogStructure { get; set; }
        /// <summary>
        /// [FrogLength]
        /// </summary>
        public Nullable<decimal> FrogLength { get; set; }
        /// <summary>
        /// [TopRailType]
        /// </summary>
        public string TopRailType { get; set; }
        /// <summary>
        /// [TopRailLength]
        /// </summary>
        public Nullable<decimal> TopRailLength { get; set; }
        /// <summary>
        /// [TurnoutAllLength]
        /// </summary>
        public Nullable<decimal> TurnoutAllLength { get; set; }
        /// <summary>
        /// [TurnoutFrontLength]
        /// </summary>
        public Nullable<decimal> TurnoutFrontLength { get; set; }
        /// <summary>
        /// [TopRailBaseLength]
        /// </summary>
        public Nullable<decimal> TopRailBaseLength { get; set; }
        /// <summary>
        /// [SwitchType]
        /// </summary>
        public Nullable<int> SwitchType { get; set; }
        /// <summary>
        /// [TopRailMileage]
        /// </summary>
        public Nullable<decimal> TopRailMileage { get; set; }
        /// <summary>
        /// [StraightSpeed]
        /// </summary>
        public Nullable<decimal> StraightSpeed { get; set; }
        /// <summary>
        /// [LateralSpeed]
        /// </summary>
        public Nullable<decimal> LateralSpeed { get; set; }
        /// <summary>
        /// [Remark]
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// [SortId]
        /// </summary>
        public Nullable<int> SortId { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航属性：BsFacilityEquipment
        /// </summary>
        public virtual BsFacilityEquipment BsFacilityEquipment { get; set; }
    }
}
