//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsWkReservoir.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:53
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [BsWkReservoir]
    /// </summary>
    [Serializable]
    public partial class BsWkReservoir : BaseEntity
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public BsWkReservoir()
        {
            this.BsMtReservoirs = new List<BsMtReservoir>();
        }

        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [LineCode]
        /// </summary>
        public string LineCode { get; set; }
        /// <summary>
        /// [SectionId]
        /// </summary>
        public string SectionId { get; set; }
        /// <summary>
        /// [SectionCode]
        /// </summary>
        public string SectionCode { get; set; }
        /// <summary>
        /// [ReservoirCode]
        /// </summary>
        public string ReservoirCode { get; set; }
        /// <summary>
        /// [ReservoirName]
        /// </summary>
        public string ReservoirName { get; set; }
        /// <summary>
        /// [AreaId]
        /// </summary>
        public string AreaId { get; set; }
        /// <summary>
        /// [WorkAreaCode]
        /// </summary>
        public string WorkAreaCode { get; set; }
        /// <summary>
        /// [IsEnabled]
        /// </summary>
        public Nullable<int> IsEnabled { get; set; }
        /// <summary>
        /// [Remark]
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// [SortId]
        /// </summary>
        public Nullable<int> SortId { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航集合：BsMtReservoirs
        /// </summary>
        public virtual ICollection<BsMtReservoir> BsMtReservoirs { get; set; }
        /// <summary>
        /// 导航属性：BsWorkArea
        /// </summary>
        public virtual BsWorkArea BsWorkArea { get; set; }
    }
}
