//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="BsWorkArea.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:53
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [BsWorkArea]
    /// </summary>
    [Serializable]
    public partial class BsWorkArea : BaseEntity
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public BsWorkArea()
        {
            this.BsCheckArrays = new List<BsCheckArray>();
            this.BsSectionAreas = new List<BsSectionArea>();
            this.BsWkReservoirs = new List<BsWkReservoir>();
            this.BsWorkAreaEmps = new List<BsWorkAreaEmp>();
        }

        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [LineId]
        /// </summary>
        public string LineId { get; set; }
        /// <summary>
        /// [LineCode]
        /// </summary>
        public string LineCode { get; set; }
        /// <summary>
        /// [WorkAreaName]
        /// </summary>
        public string WorkAreaName { get; set; }
        /// <summary>
        /// [WorkAreaCode]
        /// </summary>
        public string WorkAreaCode { get; set; }
        /// <summary>
        /// [DepartmentId]
        /// </summary>
        public string DepartmentId { get; set; }
        /// <summary>
        /// [DepartmentCode]
        /// </summary>
        public string DepartmentCode { get; set; }
        /// <summary>
        /// [UpStartMileage]
        /// </summary>
        public Nullable<decimal> UpStartMileage { get; set; }
        /// <summary>
        /// [UpEndMileage]
        /// </summary>
        public Nullable<decimal> UpEndMileage { get; set; }
        /// <summary>
        /// [UpMileagePreTag]
        /// </summary>
        public string UpMileagePreTag { get; set; }
        /// <summary>
        /// [DownStartMileage]
        /// </summary>
        public Nullable<decimal> DownStartMileage { get; set; }
        /// <summary>
        /// [DownEndMileage]
        /// </summary>
        public Nullable<decimal> DownEndMileage { get; set; }
        /// <summary>
        /// [DownMileagePreTag]
        /// </summary>
        public string DownMileagePreTag { get; set; }
        /// <summary>
        /// [IsEnabled]
        /// </summary>
        public Nullable<int> IsEnabled { get; set; }
        /// <summary>
        /// [Remark]
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// [SortId]
        /// </summary>
        public Nullable<int> SortId { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航集合：BsCheckArrays
        /// </summary>
        public virtual ICollection<BsCheckArray> BsCheckArrays { get; set; }
        /// <summary>
        /// 导航属性：BsLineInfo
        /// </summary>
        public virtual BsLineInfo BsLineInfo { get; set; }
        /// <summary>
        /// 导航集合：BsSectionAreas
        /// </summary>
        public virtual ICollection<BsSectionArea> BsSectionAreas { get; set; }
        /// <summary>
        /// 导航集合：BsWkReservoirs
        /// </summary>
        public virtual ICollection<BsWkReservoir> BsWkReservoirs { get; set; }
        /// <summary>
        /// 导航集合：BsWorkAreaEmps
        /// </summary>
        public virtual ICollection<BsWorkAreaEmp> BsWorkAreaEmps { get; set; }
    }
}
