	
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="HiddenDangerRecordMap.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2017-02-09 16:09
// </copyright>
//------------------------------------------------------------------------------

	using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace TY.ZZHidden.Data.Domain.Models.Mapping
{
    public class HiddenDangerRecordMap : EntityTypeConfiguration<HiddenDangerRecord>
    {
        public HiddenDangerRecordMap()
        {
            // Primary Key
            this.HasKey(t => t.ID);

            // Properties
            this.Property(t => t.ID)
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.CheckBy)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.BuildTermId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.DptId)
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.Remark)
                .HasMaxLength(500);

            // Table & Column Mappings
            this.ToTable("HiddenDangerRecord");
            this.Property(t => t.ID).HasColumnName("ID");
            this.Property(t => t.IsHiddenDanger).HasColumnName("IsHiddenDanger");
            this.Property(t => t.CheckBy).HasColumnName("CheckBy");
            this.Property(t => t.CheckDate).HasColumnName("CheckDate");
            this.Property(t => t.UploadDate).HasColumnName("UploadDate");
            this.Property(t => t.BuildTermId).HasColumnName("BuildTermId");
            this.Property(t => t.CompanyType).HasColumnName("CompanyType");
            this.Property(t => t.Weather).HasColumnName("Weather");
            this.Property(t => t.DptId).HasColumnName("DptId");
            this.Property(t => t.Remark).HasColumnName("Remark");
        }
    }
}
