//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="Play.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2018-03-23 09:42
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Data.Domain;
using Data.DomainMap;


//namespace TM.Data.Models
namespace  Data.Domain
{
    /// <summary>
    /// [Play]
    /// </summary>
    [Serializable]
    public partial class Play 
    {
        /// <summary>
        /// [ID]
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// [Name]
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// [Odds]
        /// </summary>
        public Nullable<double> Odds { get; set; }
        /// <summary>
        /// [ParentID]
        /// </summary>
        public string ParentID { get; set; }
        /// <summary>
        /// [OffTime]
        /// </summary>
        public Nullable<System.DateTime> OffTime { get; set; }
        /// <summary>
        /// [Status]
        /// </summary>
        public string Status { get; set; }
    }
}
