//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="Wx_CheckFile.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:53
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [Wx_CheckFile]
    /// </summary>
    [Serializable]
    public partial class Wx_CheckFile : BaseEntity
    {
        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [CheckArrangeId]
        /// </summary>
        public string CheckArrangeId { get; set; }
        /// <summary>
        /// [CheckArrangeCode]
        /// </summary>
        public string CheckArrangeCode { get; set; }
        /// <summary>
        /// [FileCode]
        /// </summary>
        public string FileCode { get; set; }
        /// <summary>
        /// [FileName]
        /// </summary>
        public string FileName { get; set; }
        /// <summary>
        /// [FilePath]
        /// </summary>
        public string FilePath { get; set; }
        /// <summary>
        /// [FileType]
        /// </summary>
        public string FileType { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航属性：Wx_CheckArrange
        /// </summary>
        public virtual Wx_CheckArrange Wx_CheckArrange { get; set; }
    }
}
