//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="Wx_CheckArrange.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:53
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [Wx_CheckArrange]
    /// </summary>
    [Serializable]
    public partial class Wx_CheckArrange : BaseEntity
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public Wx_CheckArrange()
        {
            this.Wx_CheckFile = new List<Wx_CheckFile>();
            this.Wx_CheckWorkMaterial = new List<Wx_CheckWorkMaterial>();
        }

        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [CheckProjectId]
        /// </summary>
        public string CheckProjectId { get; set; }
        /// <summary>
        /// [ArrangeCode]
        /// </summary>
        public string ArrangeCode { get; set; }
        /// <summary>
        /// [ArrangeCotent]
        /// </summary>
        public string ArrangeCotent { get; set; }
        /// <summary>
        /// [TaskState]
        /// </summary>
        public Nullable<int> TaskState { get; set; }
        /// <summary>
        /// [CheckLeaderCode]
        /// </summary>
        public string CheckLeaderCode { get; set; }
        /// <summary>
        /// [ArtificialNum]
        /// </summary>
        public Nullable<int> ArtificialNum { get; set; }
        /// <summary>
        /// [Workload]
        /// </summary>
        public string Workload { get; set; }
        /// <summary>
        /// [PracticalNumr]
        /// </summary>
        public Nullable<int> PracticalNumr { get; set; }
        /// <summary>
        /// [PlanStartDate]
        /// </summary>
        public Nullable<System.DateTime> PlanStartDate { get; set; }
        /// <summary>
        /// [PlanEndDate]
        /// </summary>
        public Nullable<System.DateTime> PlanEndDate { get; set; }
        /// <summary>
        /// [IsFinished]
        /// </summary>
        public Nullable<int> IsFinished { get; set; }
        /// <summary>
        /// [Remark]
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航集合：Wx_CheckFile
        /// </summary>
        public virtual ICollection<Wx_CheckFile> Wx_CheckFile { get; set; }
        /// <summary>
        /// 导航属性：Wx_CheckProject
        /// </summary>
        public virtual Wx_CheckProject Wx_CheckProject { get; set; }
        /// <summary>
        /// 导航集合：Wx_CheckWorkMaterial
        /// </summary>
        public virtual ICollection<Wx_CheckWorkMaterial> Wx_CheckWorkMaterial { get; set; }
    }
}
