//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="Wx_CheckWorkMaterial.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:53
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [Wx_CheckWorkMaterial]
    /// </summary>
    [Serializable]
    public partial class Wx_CheckWorkMaterial : BaseEntity
    {
        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [CheckArrangeId]
        /// </summary>
        public string CheckArrangeId { get; set; }
        /// <summary>
        /// [ReservoirMaterialId]
        /// </summary>
        public string ReservoirMaterialId { get; set; }
        /// <summary>
        /// [MaterialConfigCode]
        /// </summary>
        public string MaterialConfigCode { get; set; }
        /// <summary>
        /// [MaterialInfoId]
        /// </summary>
        public string MaterialInfoId { get; set; }
        /// <summary>
        /// [MaterialInfoCode]
        /// </summary>
        public string MaterialInfoCode { get; set; }
        /// <summary>
        /// [RequiredQuantity]
        /// </summary>
        public Nullable<int> RequiredQuantity { get; set; }
        /// <summary>
        /// [BorrowQuantity]
        /// </summary>
        public Nullable<int> BorrowQuantity { get; set; }
        /// <summary>
        /// [ReturnQuantity]
        /// </summary>
        public Nullable<int> ReturnQuantity { get; set; }
        /// <summary>
        /// [PracticalQuantity]
        /// </summary>
        public Nullable<int> PracticalQuantity { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航属性：Wx_CheckArrange
        /// </summary>
        public virtual Wx_CheckArrange Wx_CheckArrange { get; set; }
    }
}
