//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="YwDiseasePlan.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:54
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [YwDiseasePlan]
    /// </summary>
    [Serializable]
    public partial class YwDiseasePlan : BaseEntity
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public YwDiseasePlan()
        {
            this.YwDiseaseAssistUnits = new List<YwDiseaseAssistUnit>();
            this.YwDiseasePlanDetails = new List<YwDiseasePlanDetail>();
        }

        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [PlanCode]
        /// </summary>
        public string PlanCode { get; set; }
        /// <summary>
        /// [PlanStartDate]
        /// </summary>
        public Nullable<System.DateTime> PlanStartDate { get; set; }
        /// <summary>
        /// [PlanEndDate]
        /// </summary>
        public Nullable<System.DateTime> PlanEndDate { get; set; }
        /// <summary>
        /// [WorkAreaId]
        /// </summary>
        public string WorkAreaId { get; set; }
        /// <summary>
        /// [WorkAreaCode]
        /// </summary>
        public string WorkAreaCode { get; set; }
        /// <summary>
        /// [LineId]
        /// </summary>
        public string LineId { get; set; }
        /// <summary>
        /// [LineCode]
        /// </summary>
        public string LineCode { get; set; }
        /// <summary>
        /// [CheckLeaderCode]
        /// </summary>
        public string CheckLeaderCode { get; set; }
        /// <summary>
        /// [PlanState]
        /// </summary>
        public Nullable<int> PlanState { get; set; }
        /// <summary>
        /// [PlanEmpNum]
        /// </summary>
        public Nullable<int> PlanEmpNum { get; set; }
        /// <summary>
        /// [ExecStartDate]
        /// </summary>
        public Nullable<System.DateTime> ExecStartDate { get; set; }
        /// <summary>
        /// [ExecEndDate]
        /// </summary>
        public Nullable<System.DateTime> ExecEndDate { get; set; }
        /// <summary>
        /// [ExecEmpNum]
        /// </summary>
        public Nullable<int> ExecEmpNum { get; set; }
        /// <summary>
        /// [ExecRemark]
        /// </summary>
        public string ExecRemark { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航集合：YwDiseaseAssistUnits
        /// </summary>
        public virtual ICollection<YwDiseaseAssistUnit> YwDiseaseAssistUnits { get; set; }
        /// <summary>
        /// 导航集合：YwDiseasePlanDetails
        /// </summary>
        public virtual ICollection<YwDiseasePlanDetail> YwDiseasePlanDetails { get; set; }
    }
}
