//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="YwDiseaseData.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:53
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [YwDiseaseData]
    /// </summary>
    [Serializable]
    public partial class YwDiseaseData : BaseEntity
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public YwDiseaseData()
        {
            this.YwDiseaseFiles = new List<YwDiseaseFile>();
            this.YwDiseaseModifyHistories = new List<YwDiseaseModifyHistory>();
        }

        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [DiseaseDataCode]
        /// </summary>
        public string DiseaseDataCode { get; set; }
        /// <summary>
        /// [CheckTaskType]
        /// </summary>
        public Nullable<int> CheckTaskType { get; set; }
        /// <summary>
        /// [CheckTaskCode]
        /// </summary>
        public string CheckTaskCode { get; set; }
        /// <summary>
        /// [TaskDetailCode]
        /// </summary>
        public string TaskDetailCode { get; set; }
        /// <summary>
        /// [LineCode]
        /// </summary>
        public string LineCode { get; set; }
        /// <summary>
        /// [MemberConfigCode]
        /// </summary>
        public string MemberConfigCode { get; set; }
        /// <summary>
        /// [CheckArrayCode]
        /// </summary>
        public string CheckArrayCode { get; set; }
        /// <summary>
        /// [CheckLeaderCode]
        /// </summary>
        public string CheckLeaderCode { get; set; }
        /// <summary>
        /// [CheckMemberCode]
        /// </summary>
        public string CheckMemberCode { get; set; }
        /// <summary>
        /// [CheckRangeCode]
        /// </summary>
        public string CheckRangeCode { get; set; }
        /// <summary>
        /// [DiseaseId]
        /// </summary>
        public string DiseaseId { get; set; }
        /// <summary>
        /// [DiseaseCode]
        /// </summary>
        public string DiseaseCode { get; set; }
        /// <summary>
        /// [DiseaseClass]
        /// </summary>
        public Nullable<int> DiseaseClass { get; set; }
        /// <summary>
        /// [DiseaseLibCls]
        /// </summary>
        public Nullable<int> DiseaseLibCls { get; set; }
        /// <summary>
        /// [DiseaseState]
        /// </summary>
        public Nullable<int> DiseaseState { get; set; }
        /// <summary>
        /// [DiseaseRemark]
        /// </summary>
        public string DiseaseRemark { get; set; }
        /// <summary>
        /// [Suggestion]
        /// </summary>
        public string Suggestion { get; set; }
        /// <summary>
        /// [RailCode]
        /// </summary>
        public string RailCode { get; set; }
        /// <summary>
        /// [StockMark]
        /// </summary>
        public Nullable<int> StockMark { get; set; }
        /// <summary>
        /// [StockType]
        /// </summary>
        public string StockType { get; set; }
        /// <summary>
        /// [BoardNo]
        /// </summary>
        public Nullable<int> BoardNo { get; set; }
        /// <summary>
        /// [DirectionMark]
        /// </summary>
        public Nullable<int> DirectionMark { get; set; }
        /// <summary>
        /// [StartRailNo]
        /// </summary>
        public Nullable<int> StartRailNo { get; set; }
        /// <summary>
        /// [EndRailNo]
        /// </summary>
        public Nullable<int> EndRailNo { get; set; }
        /// <summary>
        /// [WriteDate]
        /// </summary>
        public Nullable<System.DateTime> WriteDate { get; set; }
        /// <summary>
        /// [FindEmpId]
        /// </summary>
        public string FindEmpId { get; set; }
        /// <summary>
        /// [FindWay]
        /// </summary>
        public Nullable<int> FindWay { get; set; }
        /// <summary>
        /// [FindDate]
        /// </summary>
        public Nullable<System.DateTime> FindDate { get; set; }
        /// <summary>
        /// [Depth]
        /// </summary>
        public Nullable<decimal> Depth { get; set; }
        /// <summary>
        /// [Width]
        /// </summary>
        public Nullable<decimal> Width { get; set; }
        /// <summary>
        /// [Length]
        /// </summary>
        public Nullable<decimal> Length { get; set; }
        /// <summary>
        /// [Area]
        /// </summary>
        public Nullable<decimal> Area { get; set; }
        /// <summary>
        /// [DiseaseNum]
        /// </summary>
        public Nullable<int> DiseaseNum { get; set; }
        /// <summary>
        /// [ChecktDate]
        /// </summary>
        public Nullable<System.DateTime> ChecktDate { get; set; }
        /// <summary>
        /// [CheckStartMileage]
        /// </summary>
        public Nullable<decimal> CheckStartMileage { get; set; }
        /// <summary>
        /// [CheckEndMileage]
        /// </summary>
        public Nullable<decimal> CheckEndMileage { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航集合：YwDiseaseFiles
        /// </summary>
        public virtual ICollection<YwDiseaseFile> YwDiseaseFiles { get; set; }
        /// <summary>
        /// 导航属性：YwDiseaseRecord
        /// </summary>
        public virtual YwDiseaseRecord YwDiseaseRecord { get; set; }
        /// <summary>
        /// 导航集合：YwDiseaseModifyHistories
        /// </summary>
        public virtual ICollection<YwDiseaseModifyHistory> YwDiseaseModifyHistories { get; set; }
    }
}
