//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="YwDiseasePlanDetail.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:54
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [YwDiseasePlanDetail]
    /// </summary>
    [Serializable]
    public partial class YwDiseasePlanDetail : BaseEntity
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public YwDiseasePlanDetail()
        {
            this.YwDiseaseMaterials = new List<YwDiseaseMaterial>();
            this.YwDiseasePlanDoWays = new List<YwDiseasePlanDoWay>();
            this.YwDiseasePlanDetailEmps = new List<YwDiseasePlanDetailEmp>();
        }

        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [DiseaseId]
        /// </summary>
        public string DiseaseId { get; set; }
        /// <summary>
        /// [PlanId]
        /// </summary>
        public string PlanId { get; set; }
        /// <summary>
        /// [DiseaseDataId]
        /// </summary>
        public string DiseaseDataId { get; set; }
        /// <summary>
        /// [DiseaseCode]
        /// </summary>
        public string DiseaseCode { get; set; }
        /// <summary>
        /// [PlanCode]
        /// </summary>
        public string PlanCode { get; set; }
        /// <summary>
        /// [PlanDetailCode]
        /// </summary>
        public string PlanDetailCode { get; set; }
        /// <summary>
        /// [DoWay]
        /// </summary>
        public string DoWay { get; set; }
        /// <summary>
        /// [DowayDesc]
        /// </summary>
        public string DowayDesc { get; set; }
        /// <summary>
        /// [PlanEmpNum]
        /// </summary>
        public Nullable<int> PlanEmpNum { get; set; }
        /// <summary>
        /// [ExecStartDate]
        /// </summary>
        public Nullable<System.DateTime> ExecStartDate { get; set; }
        /// <summary>
        /// [ExecEndDate]
        /// </summary>
        public Nullable<System.DateTime> ExecEndDate { get; set; }
        /// <summary>
        /// [ExecEmpNum]
        /// </summary>
        public Nullable<int> ExecEmpNum { get; set; }
        /// <summary>
        /// [IsCompleted]
        /// </summary>
        public Nullable<int> IsCompleted { get; set; }
        /// <summary>
        /// [FinishResult]
        /// </summary>
        public Nullable<int> FinishResult { get; set; }
        /// <summary>
        /// [ExecRemark]
        /// </summary>
        public string ExecRemark { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航集合：YwDiseaseMaterials
        /// </summary>
        public virtual ICollection<YwDiseaseMaterial> YwDiseaseMaterials { get; set; }
        /// <summary>
        /// 导航属性：YwDiseasePlan
        /// </summary>
        public virtual YwDiseasePlan YwDiseasePlan { get; set; }
        /// <summary>
        /// 导航集合：YwDiseasePlanDoWays
        /// </summary>
        public virtual ICollection<YwDiseasePlanDoWay> YwDiseasePlanDoWays { get; set; }
        /// <summary>
        /// 导航属性：YwDiseaseRecord
        /// </summary>
        public virtual YwDiseaseRecord YwDiseaseRecord { get; set; }
        /// <summary>
        /// 导航集合：YwDiseasePlanDetailEmps
        /// </summary>
        public virtual ICollection<YwDiseasePlanDetailEmp> YwDiseasePlanDetailEmps { get; set; }
    }
}
