//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="YwDiseaseRecord.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:54
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [YwDiseaseRecord]
    /// </summary>
    [Serializable]
    public partial class YwDiseaseRecord : BaseEntity
    {
        /// <summary>
        /// 构造函数
        /// </summary>
        public YwDiseaseRecord()
        {
            this.YwDiseaseDatas = new List<YwDiseaseData>();
            this.YwDiseaseEvaluates = new List<YwDiseaseEvaluate>();
            this.YwDiseasePlanDetails = new List<YwDiseasePlanDetail>();
            this.YwDiseasePushes = new List<YwDiseasePush>();
        }

        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [RecordCode]
        /// </summary>
        public string RecordCode { get; set; }
        /// <summary>
        /// [CheckDataType]
        /// </summary>
        public Nullable<int> CheckDataType { get; set; }
        /// <summary>
        /// [LineCode]
        /// </summary>
        public string LineCode { get; set; }
        /// <summary>
        /// [WorkAreaCode]
        /// </summary>
        public string WorkAreaCode { get; set; }
        /// <summary>
        /// [EquipmentCode]
        /// </summary>
        public string EquipmentCode { get; set; }
        /// <summary>
        /// [EquipmentTypeCode]
        /// </summary>
        public string EquipmentTypeCode { get; set; }
        /// <summary>
        /// [TurnouAreatCode]
        /// </summary>
        public string TurnouAreatCode { get; set; }
        /// <summary>
        /// [TurnouCode]
        /// </summary>
        public string TurnouCode { get; set; }
        /// <summary>
        /// [DiseaseTypeCode]
        /// </summary>
        public string DiseaseTypeCode { get; set; }
        /// <summary>
        /// [DiseaseOtherContent]
        /// </summary>
        public string DiseaseOtherContent { get; set; }
        /// <summary>
        /// [FacilityCode]
        /// </summary>
        public string FacilityCode { get; set; }
        /// <summary>
        /// [IsEvaluated]
        /// </summary>
        public Nullable<int> IsEvaluated { get; set; }
        /// <summary>
        /// [IsImported]
        /// </summary>
        public Nullable<int> IsImported { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航集合：YwDiseaseDatas
        /// </summary>
        public virtual ICollection<YwDiseaseData> YwDiseaseDatas { get; set; }
        /// <summary>
        /// 导航集合：YwDiseaseEvaluates
        /// </summary>
        public virtual ICollection<YwDiseaseEvaluate> YwDiseaseEvaluates { get; set; }
        /// <summary>
        /// 导航集合：YwDiseasePlanDetails
        /// </summary>
        public virtual ICollection<YwDiseasePlanDetail> YwDiseasePlanDetails { get; set; }
        /// <summary>
        /// 导航集合：YwDiseasePushes
        /// </summary>
        public virtual ICollection<YwDiseasePush> YwDiseasePushes { get; set; }
    }
}
