//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="YwGdDetail.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:54
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [YwGdDetail]
    /// </summary>
    [Serializable]
    public partial class YwGdDetail : BaseEntity
    {
        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [TaskId]
        /// </summary>
        public string TaskId { get; set; }
        /// <summary>
        /// [TaskCode]
        /// </summary>
        public string TaskCode { get; set; }
        /// <summary>
        /// [CheckRangeCode]
        /// </summary>
        public string CheckRangeCode { get; set; }
        /// <summary>
        /// [EquipmentCode]
        /// </summary>
        public string EquipmentCode { get; set; }
        /// <summary>
        /// [EquipmentType]
        /// </summary>
        public string EquipmentType { get; set; }
        /// <summary>
        /// [ExStartTime]
        /// </summary>
        public Nullable<System.DateTime> ExStartTime { get; set; }
        /// <summary>
        /// [ExEndTime]
        /// </summary>
        public Nullable<System.DateTime> ExEndTime { get; set; }
        /// <summary>
        /// [ReMark]
        /// </summary>
        public string ReMark { get; set; }
        /// <summary>
        /// [CreatTime]
        /// </summary>
        public Nullable<System.DateTime> CreatTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航属性：YwGdTask
        /// </summary>
        public virtual YwGdTask YwGdTask { get; set; }
    }
}
