//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="YwTemporaryDeatil.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:54
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [YwTemporaryDeatil]
    /// </summary>
    [Serializable]
    public partial class YwTemporaryDeatil : BaseEntity
    {
        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [TaskDetailCode]
        /// </summary>
        public string TaskDetailCode { get; set; }
        /// <summary>
        /// [TaskId]
        /// </summary>
        public string TaskId { get; set; }
        /// <summary>
        /// [TaskCode]
        /// </summary>
        public string TaskCode { get; set; }
        /// <summary>
        /// [WorkAreaId]
        /// </summary>
        public string WorkAreaId { get; set; }
        /// <summary>
        /// [WorkAreaCode]
        /// </summary>
        public string WorkAreaCode { get; set; }
        /// <summary>
        /// [NodeId]
        /// </summary>
        public string NodeId { get; set; }
        /// <summary>
        /// [NodeCode]
        /// </summary>
        public string NodeCode { get; set; }
        /// <summary>
        /// [NodeType]
        /// </summary>
        public Nullable<int> NodeType { get; set; }
        /// <summary>
        /// [Direction]
        /// </summary>
        public Nullable<int> Direction { get; set; }
        /// <summary>
        /// [RouteId]
        /// </summary>
        public string RouteId { get; set; }
        /// <summary>
        /// [RouteCode]
        /// </summary>
        public string RouteCode { get; set; }
        /// <summary>
        /// [RangeType]
        /// </summary>
        public Nullable<int> RangeType { get; set; }
        /// <summary>
        /// [StartMileage]
        /// </summary>
        public Nullable<decimal> StartMileage { get; set; }
        /// <summary>
        /// [EndmMleage]
        /// </summary>
        public Nullable<decimal> EndmMleage { get; set; }
        /// <summary>
        /// [StartMileagePrefix]
        /// </summary>
        public string StartMileagePrefix { get; set; }
        /// <summary>
        /// [EndMleagePrefix]
        /// </summary>
        public string EndMleagePrefix { get; set; }
        /// <summary>
        /// [ExStartTime]
        /// </summary>
        public Nullable<System.DateTime> ExStartTime { get; set; }
        /// <summary>
        /// [ExEndTime]
        /// </summary>
        public Nullable<System.DateTime> ExEndTime { get; set; }
        /// <summary>
        /// [ReMark]
        /// </summary>
        public string ReMark { get; set; }
        /// <summary>
        /// [CreatTime]
        /// </summary>
        public Nullable<System.DateTime> CreatTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
        /// <summary>
        /// 导航属性：YwTemporaryTask
        /// </summary>
        public virtual YwTemporaryTask YwTemporaryTask { get; set; }
    }
}
