//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="YwXjTask.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2016-12-15 09:54
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using TY.Framework.EF;
using TY.Framework.EF.Base;
using TY.Framework.ToolT4;


namespace TY.SHMetroPlan.Data.Domain.Models
{
    /// <summary>
    /// [YwXjTask]
    /// </summary>
    [Serializable]
    public partial class YwXjTask : BaseEntity
    {
        /// <summary>
        /// [Id]
        /// </summary>
        public string Id { get; set; }
        /// <summary>
        /// [LineCode]
        /// </summary>
        public string LineCode { get; set; }
        /// <summary>
        /// [WorkAreaId]
        /// </summary>
        public string WorkAreaId { get; set; }
        /// <summary>
        /// [WorkAreaCode]
        /// </summary>
        public string WorkAreaCode { get; set; }
        /// <summary>
        /// [TaskName]
        /// </summary>
        public string TaskName { get; set; }
        /// <summary>
        /// [TaskCode]
        /// </summary>
        public string TaskCode { get; set; }
        /// <summary>
        /// [TaskState]
        /// </summary>
        public Nullable<int> TaskState { get; set; }
        /// <summary>
        /// [CheckTaskType]
        /// </summary>
        public Nullable<int> CheckTaskType { get; set; }
        /// <summary>
        /// [MemberConfigCode]
        /// </summary>
        public string MemberConfigCode { get; set; }
        /// <summary>
        /// [CheckArrayCode]
        /// </summary>
        public string CheckArrayCode { get; set; }
        /// <summary>
        /// [CheckLeaderCode]
        /// </summary>
        public string CheckLeaderCode { get; set; }
        /// <summary>
        /// [CheckMemberCode]
        /// </summary>
        public string CheckMemberCode { get; set; }
        /// <summary>
        /// [CheckRangeCode]
        /// </summary>
        public string CheckRangeCode { get; set; }
        /// <summary>
        /// [ExecStartDate]
        /// </summary>
        public Nullable<System.DateTime> ExecStartDate { get; set; }
        /// <summary>
        /// [ExecEndDate]
        /// </summary>
        public Nullable<System.DateTime> ExecEndDate { get; set; }
        /// <summary>
        /// [IsUrgentTask]
        /// </summary>
        public Nullable<int> IsUrgentTask { get; set; }
        /// <summary>
        /// [StartDate]
        /// </summary>
        public Nullable<System.DateTime> StartDate { get; set; }
        /// <summary>
        /// [EndDate]
        /// </summary>
        public Nullable<System.DateTime> EndDate { get; set; }
        /// <summary>
        /// [CheckTime]
        /// </summary>
        public Nullable<decimal> CheckTime { get; set; }
        /// <summary>
        /// [CheckKilometre]
        /// </summary>
        public Nullable<decimal> CheckKilometre { get; set; }
        /// <summary>
        /// [CheckRange]
        /// </summary>
        public string CheckRange { get; set; }
        /// <summary>
        /// [DiseaseNum]
        /// </summary>
        public Nullable<int> DiseaseNum { get; set; }
        /// <summary>
        /// [Remark]
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [UpdateTime]
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
        /// <summary>
        /// [RowVersion]
        /// </summary>
        public Nullable<int> RowVersion { get; set; }
    }
}
