	
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="PlayItem.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        生成时间：2018-03-26 13:36
// </copyright>
//------------------------------------------------------------------------------

	using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;
using Data.Domain;
using Data.DomainMap;

//namespace TM.Data.Models.Mapping
namespace Data.DomainMap { 
    public class PlayItemMap : EntityTypeConfiguration<PlayItem>
    {
        public PlayItemMap()
        {
            // Primary Key
            this.HasKey(t => t.ID);

            // Properties
            this.Property(t => t.ID)
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.PlayID)
                .IsRequired()
                .IsFixedLength()
                .HasMaxLength(36);

            this.Property(t => t.Loginname)
                .HasMaxLength(50);

            this.Property(t => t.State)
                .HasMaxLength(50);

            // Table & Column Mappings
            this.ToTable("PlayItem");
            this.Property(t => t.ID).HasColumnName("ID");
            this.Property(t => t.PlayID).HasColumnName("PlayID");
            this.Property(t => t.Get).HasColumnName("Get");            
            this.Property(t => t.Loginname).HasColumnName("Loginname");
            this.Property(t => t.Cost1).HasColumnName("Cost1");
            this.Property(t => t.CreateTime).HasColumnName("CreateTime");
            this.Property(t => t.State).HasColumnName("State");
        }
    }
}
