//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="PlayItem.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        生成时间：2018-03-26 13:36
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Data.Domain;


//namespace TM.Data.Models
namespace  Data.Domain
{
    /// <summary>
    /// [PlayItem]
    /// </summary>
    [Serializable]
    public partial class PlayItem 
    {
        /// <summary>
        /// [ID]
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// [PlayID]
        /// </summary>
        public string PlayID { get; set; }
        /// <summary>
        /// [Loginname]
        /// </summary>
        public string Loginname { get; set; }
        /// <summary>
        /// [Cost1]
        /// </summary>
        public Nullable<int> Cost1 { get; set; }
        /// <summary>
        /// [Cost2]
        /// </summary>
        public Nullable<int> Cost2 { get; set; }
        /// <summary>
        /// [Get]
        /// </summary>
        public Nullable<int> Get { get; set; }

        /// <summary>
        /// [Get2]
        /// </summary>
        public Nullable<int> Get2 { get; set; }
        /// <summary>
        /// [CreateTime]
        /// </summary>
        public Nullable<System.DateTime> CreateTime { get; set; }
        /// <summary>
        /// [State]
        /// </summary>
        public string State { get; set; }
    }
}
