//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// <copyright file="userinfo.cs">
//        Copyright(c)2015   rights reserved.
//        CLR版本：4.0.30319.239
//        开发组织：李文学@上海同岩土木科技工程有限公司
//        所属工程：TY.*
//        生成时间：2018-02-01 08:58
// </copyright>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Data.Domain;

namespace  Data.Domain
{
    /// <summary>
    /// [userinfo]
    /// </summary>
    [Serializable]
    public partial class userinfo 
    {
        /// <summary>
        /// [ID]
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// [Email]
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// [Name]
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// [LoginName]
        /// </summary>
        public string LoginName { get; set; }
        /// <summary>
        /// [Card_bg]
        /// </summary>
        public string Card_bg { get; set; }
        
        /// <summary>
        /// [PSW]
        /// </summary>
        public string PSW { get; set; }
        /// <summary>
        /// [MateLoginName]
        /// </summary>
        public string MateLoginName { get; set; }
        /// <summary>
        /// [IMG]
        /// </summary>
        public string IMG { get; set; }
        
        /// <summary>
        /// [MateName]
        /// </summary>
        public string MateName { get; set; }
        /// <summary>
        /// [RemainRoll]
        /// </summary>
        public Nullable<int> RemainRoll { get; set; }
        /// <summary>
        /// [PrivateKey]
        /// </summary>
        public string PrivateKey { get; set; }
        /// <summary>
        /// [SteamID]
        /// </summary>
        public string SteamID { get; set; }
        /// <summary>
        /// [PubgID]
        /// </summary>
        public string PubgID { get; set; }
        /// <summary>
        /// [DOTA2ID]
        /// </summary>
        public string DOTA2ID { get; set; }
        /// <summary>
        /// [WechatID]
        /// </summary>
        public string WechatID { get; set; }
        /// <summary>
        /// S币数目
        /// </summary>
        public int SCrrency { get; set; }
        /// <summary>
        /// 积分数目
        /// </summary>
        public int Points { get; set; }
        /// <summary>
        /// RMB数目
        /// </summary>
        public int RMB { get; set; }
        
        /// <summary>
        /// 上香次数
        /// </summary>
        public int sacrifNum { get; set; }
    }
}
